### ISSUE TITLE
As a basecamp user, I want to get pinged only from issues that I'm subscribed to, or if I am mentioned, so that I don't get inundated with GitHub activity pings.

### ISSUE THREAD

**Issue by solares** [foundersclubsoftware/Basecamp-Github_Chatbot#22]
Is this possible with this chatbot? Am I able to parse the GitHub message and selectively ping a destination depending upon certain criteria?

**Comment by levibostian** [comment]
Hey there, @solares. Welcome. 

This project is designed to notify a whole team some repositories. It does not filter by mentions or issues you're subscribed. If you instruct GitHub issues to go to Basecamp you will get all Issues in a campfire.

**Comment by solares** [comment]
Thanks @levibostian. Would it be technically possible for us to fork this repo and attain the desired functionality by parsing the contents of the GitHub message, or do Basecamp chatbots not support this filtering?

**Comment by levibostian** [comment]
@solares It would take a little bit of work, but you should be able to, yes. You would need to add the filtering logic into the chatbot source code.
